---

# check whether java is installed
- name: determine if Java is already installed
  shell: which java
  register: java_task_installed
  changed_when: java_task_installed.rc != 0
  failed_when: no

# install java kit
- name: Ensure Java Development Kit is Installed
  become: true
  yum: pkg=java-1.7.0-openjdk-devel state=installed
  tags: java_installation

#make a tomcat group and user as we want non root user to be owner of tomcat
- name: make a tomcat group
  group:
    name: tomcat
    state: present
  tags: tomcat_group

#- name: check whether a user tomcat exists
#  shell: grep -c '^tomcat:' /etc/passwd
#  register: default_user

- name: create a tomcat user for above group
  user:
    name="tomcat"
    shell=/bin/false
    groups=tomcat
    append=yes
  become: true
  tags: tomcat_user


- name: Download Tomcat and save it into /tmp folder
  get_url:
    url: "{{ tomcat8_package_url }}"
    dest: /tmp/
  become: true
  tags: tomcat_download

- name: check folder exists or not
  shell: ls -l /opt/ | grep tomcat | awk {'print $9'}
  register: tomcat_present

- name:  Make a directory for Tomcat & extract into a particular folder
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0775
  become: true
  when: tomcat_present.stdout == 0
  tags: directory_creation
  
- unarchive:
    src: /tmp/apache-tomcat-8.5.16.tar.gz
    dest: /opt/tomcat/
    remote_src: True
  tags: tomcat_installation
  
- name: get the java_path
  shell: sudo update-java-alternatives -l | awk '{print $3}'
  register: java_path
  tags: getting_java_home

# make a directory for Tomcat Server and User Files
- name:  Make a directory for Tomcat Server and User Files
  file:
    path: /etc/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0775
  tags: directory_creation

# Copy Tomcat.service file in order to make it a service
- name: copy tomcat.service file
  template:
    src: "{{ tomcat_service }}"
    dest: /etc/systemd/system/tomcat.service
    owner: tomcat
    group: tomcat
  become: true
  tags: copying_tomcat_service

# copy tomcat server.xml file
- name: copy the tomcat8 server file
  template:
    src: "{{ server }}"
    dest: /etc/tomcat/
    owner: tomcat
    group: tomcat
  become: true
  tags: copying_server_xml

# copy tomcat user.xml file
- name: copy the tomcat8 users file
  template:
    src: "{{ tomcat_users }}"
    dest: /etc/tomcat/
    owner: tomcat
    group: tomcat
  become: true
  notify:
   - restart_tomcat8
  tags: copying_user_xml
