---
# handlers file for tomcat
- name: restart_tomcat_debian
  service: name=tomcat7 state=restarted

- name: start-tomcat
  service: name=tomcat state=started enabled=true

- name: start_apache
  service: name=httpd state=started enabled=true
